// Generated by CoffeeScript 1.6.3
(function() {
  var ChessBoard, solutionsFor,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  jQuery(function() {
    var board, drawSolution, worker;
    board = new ChessBoard({
      size: 8,
      sizePx: 600,
      canvas: $('#canvas')[0]
    });
    drawSolution = function(event) {
      $('#solve').text('Find another solution').attr('disabled', false);
      return board.drawSolution(event.data);
    };
    worker = new Worker('worker.js');
    worker.addEventListener('message', drawSolution, false);
    $('#slider').slider({
      min: 4,
      max: 26,
      value: board.size,
      slide: function(_, ui) {
        var size, t, u, _ref;
        $('.ui-slider-handle').tooltip('destroy');
        size = ui.value;
        board.setSize(size);
        $('#size').text("Size: " + size + "×" + size);
        _ref = solutionsFor(size), t = _ref[0], u = _ref[1];
        $('#solutions').text("Solutions: " + t + " total, " + u + " unique");
        return $('#solve').text('Find solution');
      }
    });
    $('#solve').click(function() {
      $(this).html('<img src="progress_bar.gif">').attr('disabled', true);
      return worker.postMessage(board.getSize());
    });
    $('#solve').tooltip({
      title: 'Press to solve puzzle',
      trigger: 'manual',
      placement: 'left'
    });
    $('.ui-slider-handle').tooltip({
      title: 'Drag to change board size',
      trigger: 'manual',
      placement: 'bottom'
    });
    $('#solve').one('click', function() {
      $(this).tooltip('destroy');
      return $('.ui-slider-handle').tooltip('show');
    });
    return $('#solve').tooltip('show');
  });

  solutionsFor = function(s) {
    return {
      4: ['2', '1'],
      5: ['10', '2'],
      6: ['4', '1'],
      7: ['40', '6'],
      8: ['92', '12'],
      9: ['352', '46'],
      10: ['724', '92'],
      11: ['2,680', '341'],
      12: ['14,200', '1,787'],
      13: ['73,712', '9,233'],
      14: ['365,596', '45,752'],
      15: ['2,279,184', '285,053'],
      16: ['14,772,512', '1,846,955'],
      17: ['95,815,104', '11,977,939'],
      18: ['666,090,624', '83,263,591'],
      19: ['4,968,057,848', '621,012,754'],
      20: ['39,029,188,884', '4,878,666,808'],
      21: ['314,666,222,712', '39,333,324,973'],
      22: ['2,691,008,701,644', '336,376,244,042'],
      23: ['24,233,937,684,440', '3,029,242,658,210'],
      24: ['227,514,171,973,736', '28,439,272,956,934'],
      25: ['2,207,893,435,808,350', '275,986,683,743,434'],
      26: ['22,317,699,616,364,000', '2,789,712,466,510,280']
    }[s];
  };

  ChessBoard = (function() {
    function ChessBoard(opts) {
      this.drawSolution = __bind(this.drawSolution, this);
      var canvas;
      this.sizePx = opts['sizePx'];
      canvas = opts['canvas'];
      canvas.width = this.sizePx;
      canvas.height = this.sizePx;
      this.ctx = canvas.getContext('2d');
      this.setSize(opts['size']);
    }

    ChessBoard.prototype.pos = function(c) {
      return c * this.tileSize;
    };

    ChessBoard.prototype.setSize = function(size) {
      this.size = size;
      this.tileSize = this.sizePx / this.size;
      return this.renderEmpty();
    };

    ChessBoard.prototype.getSize = function() {
      return this.size;
    };

    ChessBoard.prototype.renderTile = function(x, y) {
      var color;
      color = x % 2 !== y % 2 ? '#aaaaaa' : '#eeeeee';
      this.ctx.fillStyle = color;
      return this.ctx.fillRect(this.pos(x), this.pos(y), this.tileSize, this.tileSize);
    };

    ChessBoard.prototype.renderEmpty = function() {
      var x, y, _i, _ref, _results;
      _results = [];
      for (y = _i = 0, _ref = this.size; 0 <= _ref ? _i < _ref : _i > _ref; y = 0 <= _ref ? ++_i : --_i) {
        _results.push((function() {
          var _j, _ref1, _results1;
          _results1 = [];
          for (x = _j = 0, _ref1 = this.size; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; x = 0 <= _ref1 ? ++_j : --_j) {
            _results1.push(this.renderTile(x, y));
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    ChessBoard.prototype.renderQueen = function(x, y) {
      var ctx, img, s, xPos, yPos;
      img = new Image;
      img.src = 'queen.png';
      ctx = this.ctx;
      xPos = this.pos(x);
      yPos = this.pos(y);
      s = this.tileSize;
      return img.onload = function() {
        return ctx.drawImage(img, xPos, yPos, s, s);
      };
    };

    ChessBoard.prototype.drawSolution = function(solution) {
      var x, y, _i, _len, _ref, _results;
      this.renderEmpty();
      _results = [];
      for (_i = 0, _len = solution.length; _i < _len; _i++) {
        _ref = solution[_i], x = _ref[0], y = _ref[1];
        _results.push(this.renderQueen(x, y));
      }
      return _results;
    };

    return ChessBoard;

  })();

}).call(this);

/*
//@ sourceMappingURL=eight_queens.map
*/
